@startuml
hide footbox
autonumber

actor client

box "FRONTEND"
participant LoginScreen
participant PasswordRecoveryScreen
end box

box "BACKEND"
participant API
participant database
end box

client -> LoginScreen: Recuperar contraseña
LoginScreen -> API: GET /send-password-recovery-code/{email}
API -> API: validar_token

group if (token valid)
    API -> database: consultar data con el UserID
    API -> API: generar verification code
    API -> database: guardar vefirication code en el \nregistro del usuario
    API -> API: enviar al correo del usuario el codigo \nde verificacion
    client -> PasswordRecoveryScreen: insertar varification code
    group if (varification code valid)
        API -> LoginScreen: {\n\tstatus:"SUCCESS", \n\terrors:{...}, \n\tdata:{...}\n}
    else
        API -> PasswordRecoveryScreen:{\n\tstatus:"ERROR_CODE_INVALID", \n\terrors:{...}, \n\tdata:{...}\n}
    end
else
    API -> LoginScreen: {\n\tstatus:"ERROR_TOKEN", \n\terrors:{...}, \n\tdata:{...}\n}
end

@enduml
